dotnet/xliff-tasks

src/XliffTasks/XliffTasks.csproj, src/XliffTasks/build/XliffTasks.targets
FYI, @livarcocc @karajas - This just makes it so that the nupkg actually provides targets to projects that references it rather than acting as a library. The actual targets and tasks will follow separately.
=> Prepare nuget package to provide msbuild tasks

src/XliffTasks/Model/Document.cs, src/XliffTasks/Model/XlfDocument.cs
Also, remove unnecessary empty group on xlf update
=> Preserve document encoding and BOM usage

src/XliffTasks.Tests/XlfDocumentTests.cs, src/XliffTasks/Model/XlfDocument.cs
Fix #26 
@tmat Note that you'll need to delete and regenerate the roslyn-analyzers files because this does not attempt to fix up documents already corrupted by the bug.
=> Fix incorrect placement of notes on initial node creation

src/XliffTasks/Tasks/GatherXlf.cs, src/XliffTasks/Tasks/MetadataKey.cs, src/XliffTasks/Tasks/TaskItemExtensions.cs, src/XliffTasks/Tasks/UpdateXlf.cs, src/XliffTasks/build/XliffTasks.targets
Projects in the F# repo dynamically generate `<EmbeddedResource>` elements as part of a build task and that causes two specific issues that are addressed here:
1. The generated `<EmbeddedResource>` elements don't exist in the project file so the inclusion of those into the `<XlfSource>` collection can't happen at the time that `XliffTasks.targets` is imported.  The solution to this is to simply move the gathering of the sources into the `GetXlfSources` target.  (Fixes #17)
2. The F# build generates `.resx` files into the `obj\` directory which means the generated `xlf\*.xlf` files are also dropped in the `obj\` directory which means they're not included in the source tree.  The solution to this was to honor an optional metadata value `EmbeddedResource.SourceDocumentPath` which is used to …
=> enable generating .xlf files from <EmbeddedResource> elements added during the build

src/XliffTasks/build/XliffTasks.targets
If the project contains `VSCTCompile` items, those are expected to be passed to the `VSCTCompile` target in the VSSDK, but the [`GatherTranslatedSource` task](https://github.com/dotnet/xliff-tasks/blob/64820755d3a7cdc41077c8908755540eb4175040/src/XliffTasks/build/XliffTasks.targets#L132) augments that group (because [`XlfOutputItem` == "VSCTCompile"](https://github.com/dotnet/xliff-tasks/blob/64820755d3a7cdc41077c8908755540eb4175040/src/XliffTasks/build/XliffTasks.props#L44)) which means the `VSCTCompile` target must be executed _after_ `GatherTranslatedSource` has been run.
To ensure this doesn't break projects that don't reference the VSSDK, I tested it by also adding `SomeTargetNameThatDoesntExist` to the `BeforeTargets` group, which means if the `VSCTCompile` target isn't defined …
=> ensure .vsct files are translated before allowing the VSSDK to compile them

src/XliffTasks.Tests/UnstructuredDocumentTests.cs, src/XliffTasks/Model/UnstructuredDocument.cs, src/XliffTasks/Model/XlfDocument.cs, src/XliffTasks/Tasks/TransformTemplates.cs, src/XliffTasks/Tasks/XlfTask.cs, src/XliffTasks/build/XliffTasks.props, src/XliffTasks/build/XliffTasks.targets
Previously all translatable documents had some sort of absolute structure (e.g., XML), but for something like a Visual Studio project template, there was no support.  This PR is in two parts:
1.  Add `UnstructuredDocument.cs` to enable `.xlf` generation for all files in the `@(UnstructuredResource)` item group.  I'm open to suggestions for different formats for the unstructured document, but ultimately I settled on text holes that look like: `@@@StringId|This is the original English string@@@`.  This was picked because the marker `@@@` seems unlikely to appear in a file referenced by a `.vstemplate`; e.g., if the markers `{{{` and `}}}` were used, the closing marker could conceivably appear in the end of a C# file if a method, class, and namespace closing curly brace were all grouped …
=> Enable .xlf translations for unstructured documents and VS templates.

src/XliffTasks.Tests/VsctDocumentTests.cs, src/XliffTasks/Model/VsctDocument.cs
Fixes https://github.com/dotnet/roslyn/issues/23194
In a VSCT file elements are uniquely identified by a combination of GUID
and ID. However, currently XliffTasks only considers the ID and the tool
will crash if it encounters the same ID reused under multiple GUIDs.
To fix this we need to incorporate the GUID into the unique identifiers
we generate for every localizable resource. However, in repos that are
already using XliffTasks we don't want to re-label all existing
localizable items in VSCT files as that will cause a good bit of churn
and busy work for our translators. It will also make for unique
identifiers that are unnecessarily long in most cases.
To avoid this, this commit adds an extra pass over the document to first
find the IDs that are unique. Later when we create the …
=> Handle non-unique IDs in VSCT files

src/XliffTasks/XliffTasks.csproj, src/XliffTasks/build/XliffTasks.targets
1. The .targets file had a reference to netcoreapp1.1 when it really meant to have a reference to netcoreapp2.0.
2. When targeting net46 we were creating a bunch of <frameworkAssembly> elements in the .nuspec file that we don't need or want.
See the individual commits for more details.
=> Fix a couple of bugs

src/XliffTasks/XliffTasks.csproj
Set the `IsPackable` property to `true` so we start producing a package
again.
=> Create NuGet package

README.md, src/XliffTasks.Tests/XlfDocumentTests.cs, src/XliffTasks/EnumerableExtensions.cs, src/XliffTasks/Model/XlfDocument.cs, src/XliffTasks/Tasks/SortXlf.cs, src/XliffTasks/Tasks/UpdateXlf.cs, src/XliffTasks/build/XliffTasks.targets
Fixes #15.
Support sorting the `trans-unit` items in .xlf files. There are two parts to this:
1. There is a new target, `SortXlf`, with a corresponding task. When invoked it will sort all the `trans-unit` elements in the .xlf files by their `id` attributes. This is meant to be run manually, ala `msbuild /t:SortXlf`, rather than run automatically as part of the build.
2. When inserting a new `trans-unit` element we perform a linear scan for the first existing `trans-unit` that sorts _after_ the new one, and place the new one immediately before it. Thus, even if the list of `trans-unit` elements as a whole isn't sorted we still avoid the merge conflicts caused by always adding items at the end.
=> Sort XLIFF files

src/XliffTasks.Tests/XlfDocumentTests.cs, src/XliffTasks/Model/XlfDocument.cs, src/XliffTasks/Tasks/EnsureAllResourcesTranslated.cs, src/XliffTasks/build/XliffTasks.targets
Add an `EnsureAllResourcesTranslated` task and target that verifies all `trans-unit` items are in a `translated` state. If not, MSBuild errors are logged, failing the build.
Fixes #53.
=> Add a target to ensure all resources are translated

src/XliffTasks/Tasks/BuildErrorException.cs, src/XliffTasks/Tasks/UpdateXlf.cs, src/XliffTasks/Tasks/XlfTask.cs
I ran into a situation where an XLIFF file had become corrupted and the `UpdateXlf` target failed when `XDocument.Load` threw a `System.Xml.XmlException`. This resulted in MSBuild dumping out the exception message and stack trace for the failure, but not the file path as it wasn't part of the exception. Identifying the problematic file required digging through all of the .xlf files associated with the project until I found the bad one.
This change catches the `XmlException` and wraps it in a
`BuildErrorException` that includes the file path, and ensures the file
path is printed as part of the log message. The file path has been added
to a few other places where we were already throwing
`BuildErrorExceptions` as well.
=> Log better error messages when .xlf file is invalid

src/XliffTasks/EnumerableExtensions.cs, src/XliffTasks/Tasks/EnsureAllResourcesTranslated.cs, src/XliffTasks/Tasks/TaskLoggingHelperExtensions.cs
Currently, when running the `EnsureAllResourcesTranslated` target/task, each untranslated resource ID will be printed out on a separate line. The "blame" also goes to the .targets file containing the target, rather than the original .resx or .vsct. The path to that file appears in the error message.
This change re-works the error reporting to blame the original file, and joins the untranslated IDs into a single line. This should greatly reduce the output spew in the common case. The resulting error now looks like this:
```
"c:\repos\XliffTasksTest\XliffTasksTest.sln" (EnsureAllREsourcesTranslated target) (1) ->
"c:\repos\XliffTasksTest\XliffTasksTest\XliffTasksTest.csproj" (EnsureAllREsourcesTranslated target) (2) ->
(EnsureAllResourcesTranslated target) ->
MyResources.resx : error : …
```
=> Shorten error messages associated with missing resources

src/XliffTasks.Tests/ResxDocumentTests.cs, src/XliffTasks.Tests/StringExtensionsTests.cs, src/XliffTasks.Tests/XlfDocumentTests.cs, src/XliffTasks/Model/ResxDocument.cs, src/XliffTasks/Model/XlfDocument.cs, src/XliffTasks/StringExtensions.cs
Fixes #52.
Reset translations when the number of replacements changes in the source text. If the number of replacement _increases_ then until the target string is updated to a new translation formatting it will likely produce misleading or just plain meaningless text.
If the number of replacements _decreases_ then the target string will refer to replacement items that no longer exist, leading to exceptions when formatting the target.
To avoid these problem just reset the target string to the source value when we detect that they require different numbers of replacement items. The tricky bit here is correctly identifying the placeholders so we can check their indices--here I've gone with a regex and attempted to document how it works.
=> Reset translations when the number of replacements changes

src/XliffTasks.Tests/XlfDocumentTests.cs, src/XliffTasks.Tests/XliffTasks.Tests.csproj, src/XliffTasks/Model/XlfDocument.cs, src/XliffTasks/Model/xliff-core-1.2-transitional.xsd, src/XliffTasks/Model/xml.xsd, src/XliffTasks/Tasks/TaskLoggingHelperExtensions.cs, src/XliffTasks/Tasks/TranslateSource.cs, src/XliffTasks/XliffTasks.csproj
Related to #13.
When reading translations from an XLF file validate that it conforms to the XLIFF schema and report any resulting errors.
1. Embed the necessary schema (.xsd) files in the XliffTasks assembly. "xliff-core-1.2.transitional.xsd" contains the schema for the version of XLF we support, and it in turn references items from "xml.xsd".
2. Add an `XlfDocument.Validate` method. This retrieves the embedded schema files and stores them in a static `XmlSchemaSet` so we can reuse the set across multiple documents, and checks the `XlfDocument` against the schema.
3. Run validation before using the `XlfDocument` to translate a source document. If validation fails, report the problems through the MSBuild logger and return an empty set of translations--if the document doesn't validate, then …
=> Validate XLF files

build/build.ps1
Related to https://github.com/dotnet/announcements/issues/77.
In July 2018 https://dot.net switched to supporting TLS 1.2 only. PowerShell scripts will generally use TLS 1.1, meaning that our CI builds now fail when trying to retrieve the dotnet-install.ps1 script.
This commit ensures that anywhere we need to `Invoke-WebRequest` we are using TLS 1.2.
=> Use TLS 1.2 for web requests

src/XliffTasks.Tests/XElementExtensionsTests.cs, src/XliffTasks.Tests/XlfDocumentTests.cs, src/XliffTasks/Model/XElementExtensions.cs, src/XliffTasks/Model/XlfDocument.cs, src/XliffTasks/Model/XlfNames.cs
Recent localization PRs into various repos using XliffTasks sometimes deleted the `target` child of a `trans-unit` element when no translation was available. This led to `NullReferenceException`s in XliffTasks when we attempted to retrieve the translations.
It turns out that, according to the XLIFF spec, the `target` child is optional, and even where it is present its `state` attribute is also optional. These changes bring our handling of `target` and `state` in line with the spec by defining and adopting a number of helper methods for getting and setting the various children of `trans-unit` elements. In particular, these children return us the value of `source` element when the `target` is unavailable, and report the `state` as "new" when it is not defined.
Similarly, when setting the …
=> Handle missing elements and attributes

src/XliffTasks/Model/xliff-core-1.2-transitional.xsd
The xliff-core-1.2-transitional.xsd schema file imports the xml.xsd
schema file, and we include a local copy of the xml.xsd for use in
validation. However, the XLIFF schema file imports xml.xsd from a
URL--and it appears that this sometimes causes us to try and download
xml.xsd from the internet. It also seems to mean that our `XmlSchemaSet`
ends up with duplicate copies, leading it to fail with errors to the
effect that "xml:lang has already been declared".
Since we've got our own copy of xml.xsd already, here we update our copy
of xliff-core-1.2-transitional.xsd to remove the URL and avoid any
issues with reading it from online, or duplicate definitions.
=> Don't pull schema files from the internet

src/XliffTasks/build/XliffTasks.props, src/XliffTasks/build/XliffTasks.targets
Starting in Visual Studio 2019, this property is no longer required to be set - and only increases the working set and allocations in a large solution. While VS 2017 and lower still respects it, it is not needed as these come from NuGet packages and they are immutable and therefore do not need to be inputs into csc.
=> Remove MSBuildAllProjects property

src/XliffTasks.Tests/VsctDocumentTests.cs, src/XliffTasks/Model/VsctDocument.cs
Not all bitmaps have hrefs, some refer to built-in resources.
=> Do not null reference when Bitmaps have no href

eng/azure-pipelines.yml
Ensures that we won't lose publishing when we disable the release pipeline
=> Enable stages for xliff tasks

src/XliffTasks/build/XliffTasks.targets
We wouldn't ordinarily be pulled into a design-time build, but in some circumstances additional build customization might pull in a target that would trigger us to run in a design-time build. If that happens, do not enforce that XLF is up to date for several reasons:
1. It can be relatively slow and the validation can wait until a real build.
2. The eventual real build may be configured to update-on-build, making any error from design-time-build false positives.
3. Any error in the design time build without ContinueOnError will stop it from making critical progress. (We could fix this one with the appropriate continue on error, but we'd still have the above.)
Fix #36 
Fix #233
=> Do not check for out-of-date XLF in design-time builds

eng/Versions.props
Remove the restoreSources node in versions.props. It looks like we don't need any of these feeds judging by this test official build:
https://dnceng.visualstudio.com/internal/_build/results?buildId=839791&view=results
fixes https://github.com/dotnet/xliff-tasks/issues/368
=> Remove restoresources from versions.props

src/XliffTasks.Tests/XamlRuleDocumentTests.cs, src/XliffTasks/Model/XamlRuleDocument.cs
Support translation of `SearchTerms` metadata on properties in CPS rules stored in .xaml format. If we find an attribute named "Value" and it has a sibling attribute named "Name" with a value "SearchTerms", we assume we are looking at the `SearchTerms` metadata on a property.
These search terms are ultimately used by the new property pages UI to support user searches, so we need to be able to localize the terms.
=> Support translation of SearchTerms

eng/SourceBuild.props, eng/SourceBuildPrebuiltBaseline.xml, eng/Version.Details.xml, eng/azure-pipelines.yml, eng/source-build-patches/0001-remove-netcoreapp2.1-targets.patch
This enables 'source-build', which makes it easier to build the entire shipping .NET SDK from source.
This is the first and second step of arcade-powered-source-build:
https://github.com/dotnet/source-build/blob/master/Documentation/planning/arcade-powered-source-build/README.md
See https://github.com/dotnet/xdt/pull/352 for a similar PR, that this is based on.
=> Add local + ci for source-build build infra

eng/azure-pipelines-codeql.yml
Enable publishing to TSA when the CodeQL pipeline is run.
=> Enable TSA publish when using CodeQL

eng/SourceBuild.props
This is no longer used after https://github.com/dotnet/xliff-tasks/pull/509.  No source-build patches should ever be made in the future therefore this target should get cleaned up.
=> Remove unused source-build ApplySourceBuildPatchFiles target

src/XliffTasks.Tests/XamlRuleDocumentTests.cs, src/XliffTasks.Tests/XliffTasks.Tests.csproj, src/XliffTasks/Model/XamlRuleDocument.cs, src/XliffTasks/XliffTasks.csproj
RESX files have a natural "comment" field that maps to the TranslatableNode.Note. For XAML rule files, there has been no such obvious way to support adding these kinds of comments for translators.
It's useful to be able to leave comments about particular translatable strings for localisation.
I couldn't find a better way of adding these notes than via XML comments. I tried using attached properties and using mc:Ignorable, but it caused the Project Properties UI to fail to load pages with these attributes. So instead I settled for this non-type-safe approach.
=> Support XLF comments in XAML rule files

eng/SourceBuildPrebuiltBaseline.xml, eng/Version.Details.xml, src/XliffTasks/XliffTasks.csproj
Fixes https://github.com/dotnet/xliff-tasks/issues/650
Fixes https://github.com/dotnet/source-build/issues/2201
This PR does two things
1. Downgrade the Microsoft.NETCore.App from 2.2.8 to 2.0.0.  Since 2.2 is EOL, it shouldn't be referenced.  2.0.0 is something compatible with source-build.  https://github.com/dotnet/xliff-tasks/issues/657 tracks a long term solution which would remove this dependency all together.
2. Enable source-build prebuilt detection.  This would have caught this issue before it was checked in.
=> Downgrade the Microsoft.NETCore.App reference to 2.0.0

.config/tsaoptions.json, eng/azure-pipelines-codeql.yml
Swap Guardian for CodeQL 3000 Azure DevOps extension for CodeQL static code analysis.
Successful test build (minus TSA publish): [Pipelines - Run 2012777](https://dev.azure.com/dnceng/internal/_build/results?buildId=2012777&view=results)
Part of dotnet/arcade#11151
=> Use CodeQL 3000 instead of Guardian

src/XliffTasks.Tests/XamlRuleDocumentTests.cs, src/XliffTasks/Model/XamlRuleDocument.cs
Currently, there is no ability to allow arbitrary values other than DisplayName, Description, or Value _where Name="SearchTerms"_. This PR relaxes the restriction on Value attributes not named `SearchTerms` to allow them to be marked as translatable if and only if a property named IsTranslatable, with a namespace corresponding to this repo's url (https://github.com/dotnet/xliff-tasks) is marked as true.
Ex:
This allows us to do:
```xaml
<ValueEditor EditorType="MultiStringSelector">
<ValueEditor.Metadata>
<NameValuePair Name="TypeDescriptorText" Value="Custom symbols" xliff:IsTranslatable="true" />
<NameValuePair Name="AllowsCustomStrings" Value="True" />
<NameValuePair Name="ShouldDisplayEvaluatedPreview" Value="True" />
</ValueEditor.Metadata>
</ValueEditor>
```
where …
=> Allow arbitrary properties with a "Value" to be translatable

src/XliffTasks.Tests/XamlRuleDocumentTests.cs, src/XliffTasks/Model/XamlRuleDocument.cs
The purpose of this PR is to allow:
- attributes/elements deeply nested (>2 parents) to be expressed as a translatable node with a descriptive id, and to
- allow translatable nodes to be expressed as a descendent element instead of an attribute value. see below example:
```xml
<A Name="MyName">
<A.Description>MyName Description</A.Description> 
<B>
<C>
<D>
<NameValuePair Name="SearchTerms" TranslatableProp1="this-is-translated" xliff:LocalizedProperties="TranslatableProp1"> 
<NameValuePair.Value>My Search Terms</NameValuePair.Value> 
</D>
....
```
=> [xaml] Handle deeply nested translation attributes, allow translatable values to be expressed as a descendent element instead of attribute

eng/Version.Details.xml, eng/Versions.props, src/XliffTasks.Tests/XliffTasks.Tests.csproj, src/XliffTasks/XliffTasks.csproj
1. Upgrade MSBulid package versions to not bring in old netstandard1.x assets. Use the latest available version in SBRP.
2. Use the floating TFM versions defined in Arcade.
3. Consolidate version properties in Versions.props to "<PackageIdentity>Version" instead of the mix of the former and "<PackageIdentity>PackageVersion".
=> Upgrade MSBuild package versions & use floating TFMs
